### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/native_messenger#4]
- [ ] src/native_main.nim has `VERSION` set to the right value
- [ ] You've pushed it and the build works
- [ ] Give it a tag and push it

---

Aftermath:

- [ ] update native install scripts to reference the new artefacts on the main Tridactyl repo
